### ISSUE TITLE
Unresolved 'resume DG with the -r flag enabled'

### ISSUE THREAD

**Issue by Phylloxera** [khyox/draftGenomes#2]
Hi,
Sorry about the [two issues in one](https://github.com/khyox/draftGenomes/issues/1). Since the other one remains unresolved, I am making it a separate issue now.
`./draftGenomes. py -t 2`
FAILED! Unexpected EOF while parsing file AAAD01.1.fsa_nt.gz. Is it corrupted?
NOTE: You can try to solve any issue and resume
the process using the -r/--resume flag.
Then the following iterated 4X:
```
rm AAAD01.1.fsa_nt.gz
./draftGenomes.py -t 2 -r
```
all with the same error between iterations
I did this on both ubuntu and centos linux systems with the same result. Would you double check that you don't also replicate on your system?

Thanks!

**Comment by khyox** [comment]
It was not a complaint about the 2 issues, it was just for me to organize the reply, but thank you for opening another specific one. Replicated! 👍 

Anyway, it seems that, interestingly, both issues are quite related! The AAAD01 project was an existing bacterial WGS project still reported by the NCBI CGI script `taxid2wgs.cgi` but it is not there anymore (https://www.ncbi.nlm.nih.gov/Traces/wgs/?page=1&view=all&search=AAAD01). So, when downloading such project the server sends a gzipped empty file (ftp://ftp.ncbi.nlm.nih.gov/sra/wgs_aux/AA/AD/AAAD01/). DG thinks that premature EOF comes from file corruption but in this case, it is caused by an empty file. I think I will add some code to parse this specific case, but I will contact NCBI support again as this is an additional but related problem to the format change (by the way, it seems that the undocumented format changes have been done since Feb 20).

**Comment by khyox** [comment]
Update: NCBI was not aware of this problem and they are now looking into fixing the CGI.

**Comment by khyox** [comment]
Update: NCBI reports to be looking into this anomaly and any other that their CGI could be retrieving. They appreciate our patience while they solve this.

**Comment by khyox** [comment]
For future reference, this relates to NCBI Case #: CAS-408763-V0F4P2

**Comment by khyox** [comment]
NCBI support has closed the case (CAS-408763-V0F4P2) after the following:

> 1) The present of AAAD01 is an anomaly due to mislabeling somewhere. This project was removed from the list.
> 2) the 6-letter projects should start to get input the system (there is delay in having the information percolated up to blast services)
> 3) for bacteria there are over 85K 6-letter project in the list already

After giving some time for the blast services to be updated with those changes, I will work on a new release of draftGenomes compliant with the new output of the CGI script.

**Comment by khyox** [comment]
Sorry, no time for the major update required to keep this running after the important NCBI changes!
